export const mySampleData = {
  products: [
    {
      name: 'Sweet Blue - TOMMY HILFIGER',
      slug: 'tommy-hilfiger-sweet-blue-s/s-shirt',
      category: "Men's Dress Shirts",
      description: 'Sweet Blue - TOMMY HILFIGER S/S SHIRT',
      images: ['/images/products/1-1.jpeg', '/images/products/1-2.jpeg'],
      price: 42.99,
      brand: 'TOMMY HILFIGER',
      rating: 4.9,
      numReviews: 10,
      stock: 12,
      isFeatured: true,
      banner: 'banner-one.jpeg',
    },
    {
      name: 'Desert Sky - TOMMY HILFIGER',
      slug: 'tommy-hilfiger-desert-sky-s/s-shirt',
      category: "Men's Dress Shirts",
      description: 'Desert Sky - TOMMY HILFIGER S/S SHIRT',
      images: ['/images/products/2-1.jpeg', '/images/products/2-2.jpeg'],
      price: 48.99,
      brand: 'TOMMY HILFIGER',
      rating: 4.5,
      numReviews: 8,
      stock: 2,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Optic White - TOMMY HILFIGER',
      slug: 'tommy-hilfiger-optic-white-s/s-shirt',
      category: "Men's Dress Shirts",
      description: 'Optic White - TOMMY HILFIGER S/S SHIRT',
      images: ['/images/products/3-1.jpeg', '/images/products/3-2.jpeg'],
      price: 40.99,
      brand: 'TOMMY HILFIGER',
      rating: 4.8,
      numReviews: 18,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Brilliant Orange - TOMMY HILFIGER',
      slug: 'tommy-hilfiger-brilliant-orange-classic-stp-rf-shirt',
      category: "Men's Dress Shirts",
      description: 'Brilliant Orange- TOMMY HILFIGER CLASSIC STP RF SHIRT',
      images: ['/images/products/4-1.jpeg', '/images/products/4-2.jpeg'],
      price: 55.99,
      brand: 'TOMMY HILFIGER',
      rating: 4.5,
      numReviews: 8,
      stock: 2,
      isFeatured: true,
      banner: 'banner-one.jpeg',
    },
    {
      name: 'Sweet Blue - TOMMY HILFIGER',
      slug: 'tommy-hilfiger-sweet-blue-flex-poplin-rf-shirt',
      category: "Men's Dress Shirts",
      description: 'Sweet Blue - TOMMY HILFIGER FLEX POPLIN RF SHIRT',
      images: ['/images/products/5-1.jpeg', '/images/products/5-2.jpeg'],
      price: 42.99,
      brand: 'TOMMY HILFIGER',
      rating: 4.9,
      numReviews: 5,
      stock: 11,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Aerean Sea- TOMMY HILFIGER',
      slug: 'tommy-hilfiger-aerean-sea-flex-poplin-rf-shirt',
      category: "Men's Dress Shirts",
      description: 'Aerean Sea- TOMMY HILFIGER FLEX POPLIN RF SHIRT',
      images: ['/images/products/6-1.jpeg', '/images/products/6-2.jpeg'],
      price: 47.19,
      brand: 'TOMMY HILFIGER',
      rating: 4.7,
      numReviews: 15,
      stock: 13,
      isFeatured: true,
      banner: null,
    },
  ],
};
export default mySampleData;
